### ISSUE TITLE
Cambiar footer

### ISSUE THREAD

**Issue by sergioviera** [UTN-FRD/espa33#10]
Cambiar el <div class="footer">

Ocultar el contenido actual (dejarlo como comentario de HTML)

Mostrar "Desarrollado por Software Factory LSI" con referencia al link http://lsi.no-ip.org/

**Comment by fedesanches** [comment]
No se puede ver el footer

![15991821_1465210480157174_2068330082_o](https://cloud.githubusercontent.com/assets/11559273/21782978/26489b20-d694-11e6-9d25-7160881afcf4.png)

**Comment by juanbono** [comment]
Le hice un 
```
git revert e5d9c28f83affb6f46118663762eedba29f0964b
```
Deshaciendo los cambios que hacia ese commit (el de Martina). Por lo que ahora se ve todo lo que ocultaba ese commit y tambien deberia haber un par de css menos jajaja. Ahora esta visible el footer y un par de opciones que el [commit](https://github.com/UTN-FRD/espa33/commit/e5d9c28f83affb6f46118663762eedba29f0964b) ponia como hidden.
Igualmente, por cualquier cosa, se puede seguir viendo lo que reverti en el [historial de commits](https://github.com/UTN-FRD/espa33/commits/master) del repo.
Saludos!
