### ISSUE TITLE
No funciona la lista de informes

### ISSUE THREAD

**Issue by brunosagaste** [UTN-FRD/espa33#15]
No funcionan ninguno de los siguientes informes:
-Adquisición
-Búsqueda de copia
-List
-Títulos duplicados
-Búsqueda de Miembros
-Historial de Artículos Pedidos
-Lista de socios con artículos pendientes de devolución
-Listado de bibliografía prestada
-Mantener las peticiones de préstamo que contienen información de contacto con el socio
-Bibliografías más populares

**Comment by MicaelaUTN** [comment]
Lo que estaría bueno seria que al momento de buscar los libros en préstamo te aparezca una sola lista con usuarios morosos, porque ahora te da la opción de buscarlos solo en un rango, por ejemplo, del 10 al 18 de agosto, pero lo que seria mejor es que aparezcan todos a la vez, sin importar la fecha
