### ISSUE TITLE
Cambiar sección cabecera

### ISSUE THREAD

**Issue by sergioviera** [UTN-FRD/espa33#7]
Hay una tabla html que empieza con el siguiente comentario:

     **************************************************************************************
     * Library Name and hours
     **************************************************************************************

Hay que eliminar esa tabla y cambiarla por un ROW de bootstrap, manteniendo el mismo contenido (utilizando 2 columnas de 6)

**Comment by Frannutn** [comment]
http://bootstrapdocs.com/v3.3.6/docs/css/#grid :)

**Comment by juanbono** [comment]
Asi es como se veia la cabecera antes de reemplazar la tabla por una row.
Lo dejo para que quede como ayuda.

![antes](https://cloud.githubusercontent.com/assets/2772065/22076409/b2eab620-dd8e-11e6-9d8d-a7a8200353f3.jpg)
